---
# This file is managed centrally by modulesync
#   https://github.com/maestrodev/puppet-modulesync

before_install:
  - rm -f Gemfile.lock

rvm:
  - "2.0.0"

env:
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.5.0"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.2.0"

matrix:
  exclude:
    # No support for Ruby 2.0 before Puppet 3.2
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.0.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.1.0"
    # Puppet < 3.5.0 is broken under ruby 2.1 https://tickets.puppetlabs.com/browse/PUP-1243
    - rvm: 2.1.0
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.1.0
      env: PUPPET_VERSION="~> 3.0.0"
    - rvm: 2.1.0
      env: PUPPET_VERSION="~> 3.1.0"
    - rvm: 2.1.0
      env: PUPPET_VERSION="~> 3.2.0"
    - rvm: 2.1.0
      env: PUPPET_VERSION="~> 3.3.0"
    - rvm: 2.1.0
      env: PUPPET_VERSION="~> 3.4.0"

deploy:
  provider: puppetforge
  user: 
  password:
    secure: "Otm0EXhVvdcqG80+M7bQy6gy+xv/x2hJuQm1PyscRAX7zSnHNDgv85DniqGPxnJlLKxjrWwLwzDQ1+UO5WpaBn0/Oiv2U+M8VrmKq9/YkO3XgL93HZNmKKpJnj+SBR6ZaCml00AbwfTLOOBkUBMHwLDlpkClSvB79rYmKJxkDh0="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    condition: "$PUPPET_VERSION = '~> 3.6.0'"
